### ISSUE TITLE
Accuracy with NN drops, compared to GLM 

### ISSUE THREAD

**Issue by StaelTchinda** [aleximmer/Laplace#137]
Hi, 
first, thank you for this library. I do appreciate a lot the work.

I made experiments to compute the laplace approximation and then evaluate the resulting bayesian model.
I did observe that the accuracy of the bayesian model is similar to the original when using "glm" as predictions type. But it significantly drops when using "nn" as prediction type.

I did experience this situation with different networks. But a simple example was a fully connected layer applied on the IRIS dataset.:
```
FeedForward(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=4, out_features=16, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=16, out_features=8, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.2, inplace=False)
    (6): Linear(in_features=8, out_features=3, bias=True)
  )
```
With "glm", I obtain an accuracy of 1 on validation dataset, but with "nn" it drops to 0.25.

**Comment by aleximmer** [comment]
Hi, this is somewhat expected behavior for the NN predictive, see https://proceedings.mlr.press/v130/immer21a.html. However, you can control this by increasing the prior precision of the Laplace approximation using the `prior_precision` argument. Setting it high enough can always make the NN predictive work as well but we recommend using the default `glm` for the reasons explained in the linked paper.

**Comment by StaelTchinda** [comment]
Thank you for the fast reply. 
Glad to see it does not come from my implementation.

I preferred to use the NN predictive as I want to make 2 additional analysis:
- analyze the output (mean and variance) of each submodule by adding a forward hook 
- analyze the output when the model is pruned
These approaches will however not work with GLM predictive, because the original model does not seem to be called. Do you have recommendations for me to do the above tasks with GLM predictive ?

**Comment by aleximmer** [comment]
I think if you modify weights, e.g., set them to zero during pruning, it should still be reflected in the GLM predictive as well. However, getting layer-wise predictive uncertainties is more tricky and requires computing the Jacobians per layer manually, I think.

**Comment by StaelTchinda** [comment]
About the pruning, it seems a bit more complex. I see changes in the performance after pruning, so I assume the pruning is effective. However, when I undo the pruning, the performance is still bad. Can it be that the backend still stores information from previous runs ?

About the jacobians, it seems to be the most intuitive approach, however very arduous, as I would have to make it a new forward pass per layer. My intuition tells me that if I average the jacobians \nabla of shape (batch, parameters, outputs) over the last dimension (outputs), I could already obtain information from it

**Comment by StaelTchinda** [comment]
1- It did come from my implementation. I used additional dropout layers to use Monte Carlo Dropout, however some of them were either still in training in eval or applied multiple times. Which led to bad performance.

2- I could not find an intuitive way to deal with it, so I sticked to Monte Carlo Dropout to estimate the uncertainty values for this approach.
