### ISSUE TITLE
Saving a laplace approximation module after `fit`

### ISSUE THREAD

**Issue by PaulScemama** [aleximmer/Laplace#140]
Hi,

Thanks for the fantastic library. Is there any way to save a laplace approximation object after fitting it to data? So that at a later time one can load it back to produce predictions with? 

Thanks!

**Comment by runame** [comment]
Hi, we haven't implemented this feature yet (#45), but you can try using the hacky workaround described [here](https://github.com/aleximmer/Laplace/issues/42#issuecomment-948548676). Hope this helps!

**Comment by PaulScemama** [comment]
@runame fantastic, this will work for now. Thanks!
