### ISSUE TITLE
Fix defaults and suggestions

### ISSUE THREAD

**Issue by aleximmer** [aleximmer/Laplace#147]
In contrast to the redux paper, we give an example with post-hoc Laplace and marginal likelihood prior precision tuning in the docs (https://aleximmer.github.io/Laplace/#full-example-post-hoc-laplace-on-a-large-image-classifier). This is confusing and we have not thoroughly tested this approach but only recommended full + online marglik or last-layer + validation-based prior tuning.

**Comment by wiseodd** [comment]
For sequential decision making (BO & contextual bandits), there doesn't seem to be any difference between post-hoc and online marglik, in my experience. See 

* https://arxiv.org/abs/2310.00137
* https://arxiv.org/abs/2304.08309

I also observed this in my latest [BO-with-LLM paper](https://arxiv.org/abs/2402.05015), although the results are not published. 

I think it's a matter of putting this as a caveat in the README.
