### ISSUE TITLE
Add linting and formatting via `ruff`

### ISSUE THREAD

**Issue by runame** [aleximmer/Laplace#152]
Use [ruff](https://github.com/astral-sh/ruff) for linting and formatting.

**Comment by wiseodd** [comment]
I've been personally used `ruff`, for both linting and formatting, for a while. Its default setting is satisfactory. So let's go ahead with this.

I guess we still need to decide if we want single quote or double quote for string literals. But this is easy for `ruff`---currently in the `mc-subset2` branch I have the following config, to conform to the current convention:
https://github.com/aleximmer/Laplace/blob/bd5501cd96e7f3bc0d189b4a9632429f6eef31ec/pyproject.toml#L8-L9
