### ISSUE TITLE
Laplace Transform and Inverse laplace Transform for 2D images 

### ISSUE THREAD

**Issue by qm-intel** [aleximmer/Laplace#155]
@runame @aleximmer I am wondering if there is any implementation of Laplace Transform and Inverse Laplace Transform available for 2D data (i.e., images). For example, a batch of `N` input sequence of `D` can be reshaped into a 2D image with width of `W` and height of `H` and then 2D FFT is applied in both directions and then after processing it in the frequency domain, will be transformed back to the spatial domain using Inverse FFT, the `pytorch deep learning library` had the functions as follows:

```
    # x: (B x N x D)  the token features, B x H x W x D (where N = H * W), B: batch size
    # K: the frequency-domain filter, H x W_hat x D (where W_hat = W // 2 + 1)
    X = rfft2(x, dim=(1, 2))
    X_tilde = X * K
    x = irfft2(X_tilde, dim=(1, 2))

```

Is there any similar implementation for Laplace Transform in `Laplace` Library? 
Or is there any way to obtain such Laplace Transform for 2D images with current functions available in Laplace?

Thanks

**Comment by aleximmer** [comment]
@qm-intel I think this is a misunderstanding. Our library provides implementations of Laplace approximations and not Laplace transforms.

**Comment by qm-intel** [comment]
@aleximmer Thanks for mentioning it
