### ISSUE TITLE
Make try-except statement in `_gridsearch` more specific

### ISSUE THREAD

**Issue by runame** [aleximmer/Laplace#157]
Currently, if there is, e.g., any `RuntimeError` in the `loss`, `_gridsearch` will silently fail and just return the boundary value of the grid; see [here](https://github.com/aleximmer/Laplace/blob/main/laplace/baselaplace.py#L288-L302). One example for this is when the loss function is not appropriate for the setting.

**Comment by wiseodd** [comment]
@runame will this be fixed by #156, which has been addressed? Or, do you have another approach in mind?
