### ISSUE TITLE
Fit function of FullLLLaplace runs slower in Github version in comparison to pip version

### ISSUE THREAD

**Issue by MJordahn** [aleximmer/Laplace#193]
Hello,

After having installed the new version of Laplace as specified in [#191 ](https://github.com/aleximmer/Laplace/issues/191#issuecomment-2147695295), I am getting much slower fitting times using the `FullLLLaplace` module. I use the exact same code base only exchanging the version of Laplace (and new dependencies of the Github version). Running on the same GPU (Titan V) I time the `fit` function to take approximately 10 seconds in the pip version and 1805 seconds in the Git. I am also getting a user warning in the Git version, which I do not get using the pip version:

```
/home/mikkjo/.conda/envs/ude/lib/python3.12/site-packages/torch/autograd/graph.py:744: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at ../aten/src/ATen/cuda/CublasHandlePool.cpp:135.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
```

Am I supposed to be calling the `init` or `fit` functions differently in the Git version which may be the cause of the difference in fit time?

**Comment by wiseodd** [comment]
Hmm interesting. The major change would be `AsdlGGN` -> `CurvlinopsGGN` as the default backend. Could you try this and let me know the runtime?

```diff
+from laplace.curvature import AsdlGGN

...

la = Laplace(
    model,
    ...
+    backend=AsdlGGN,
)
la.fit(train_loader)
```

**Comment by MJordahn** [comment]
Using the AsdlGGN backend the `fit` time is now back to the old version (10 seconds approx) and I am not getting the Cuda context warning any longer. So seems it is related to `CurvlinopsGGN`?

The warning stems from https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/cuda/CublasHandlePool.cpp, but I am not sure if it is useful. There is a comment above the warning stating:
```
// workaround for corner case where a primary context exists but is not
// the current context, seen in multithreaded use-cases
```

I thought that perhaps the issue was related to using `num_workers>1`, but setting this to 0 in my training loader, the warning still persists for `CurvlinopsGGN`.

**Comment by wiseodd** [comment]
As for grid search, please open a separate issue---let's discuss it there for clarity sake! Thanks!

**Comment by MJordahn** [comment]
The full call to Laplace is as follows (I have included arguments for `.fit` and `.optimize_prior_precision` in case it is of interest):
```
llla_model = FullLLLaplace(
          self.model,
          likelihood='classification',
          backend = AsdlGGN,
)

llla_model.fit(train_loader)

llla_model.optimize_prior_precision(
          method='gridsearch',
          val_loader=val_loader,
          pred_type='nn',
          link_approx='mc',
          n_samples = 100,
          grid_size = 21,
          log_prior_prec_min = -4,
          log_prior_prec_max = 4,
          progress_bar = True,
)
```

**Comment by wiseodd** [comment]
I talked to @f-dangel, the author of [f-dangel/curvlionps-for-pytorch](https://github.com/f-dangel/curvlinops/tree/main). The issue is because of this line(s):

https://github.com/aleximmer/Laplace/blob/83c5de70bb976a4266fe2c66f06f8726eba669fe/laplace/curvature/curvlinops.py#L117-L120

It is implemented as for-loop over num. of parameters => slow.


I would put warning messages to inform users about their choice of backend + Laplace type. I will also decouple the Jacobian computation in the GLM predictive to use whatever is best for the situtation (e.g. does one need to backprop through the predictive?) instead of it being tied to the choice of backend.

@MJordahn thanks again for bringing this issue to our attention!

**Comment by sunyinqi0508** [comment]
> I talked to @f-dangel, the author of [f-dangel/curvlionps-for-pytorch](https://github.com/f-dangel/curvlinops/tree/main). The issue is because of this line(s):
> 
> https://github.com/aleximmer/Laplace/blob/83c5de70bb976a4266fe2c66f06f8726eba669fe/laplace/curvature/curvlinops.py#L117-L120
> 
> It is implemented as for-loop over num. of parameters => slow.
> 
> I will put warning messages to inform users about their choice of backend + Laplace type. I will also decouple the Jacobian computation in the GLM predictive to use whatever is best for the situtation (e.g. does one need to backprop through the predictive?) instead of it being tied to the choice of backend.
> 
> @MJordahn thanks again for bringing this issue to our attention!

This line will also cause an exception when pytorch's default device is set to cuda. scipy.LinearOperator.__matmul__ will simply convert the multiplier from a cuda tensor to a numpy array, but cuda tensors need to be moved to cpu before it can be converted to a numpy array. I get past this by changing the multiplier to np.eye(linop.shape[0]), but this would mean the matmul is done on cpu.

**Comment by wiseodd** [comment]
The above would indeed be the limitations of `curvlinops`. I would suggest to simply use `hessian_factorization=kron`---it should work best for all problems I could imagine. 

If you must use the full GGN/Hessian (would be curious for what applications!), then the `asdl` backend should be used.
