### ISSUE TITLE
FeatureExtractor and Python <3.11 

### ISSUE THREAD

**Issue by Ludvins** [aleximmer/Laplace#195]
With the latest update, the FeatureExtractor class requires Python >= 3.11 due to `*([0] * n_intermediate_dims)` [link](https://github.com/aleximmer/Laplace/blob/83c5de70bb976a4266fe2c66f06f8726eba669fe/laplace/utils/feature_extractor.py#L108C40-L108C68). This raises an InvalidSyntax error due to _"Unpack operator in subscript requires Python 3.11 or newer"_ if using Python 3.10 for example.

**Comment by wiseodd** [comment]
Interesting, I always assumed that it works in all cases. I personally uses Python 3.12 for the pattern matching and the Rust-like compiler error messages.

Will work fix this.

> [!NOTE]
> At a glance, the fix seems easy---just remove that unpack operator `*`.

In any case, this shouldn't happen again when the Github actions in https://github.com/aleximmer/Laplace/pull/176 are deployed (checked agains Python 3.9).
