### ISSUE TITLE
Add "Contributing" section to README

### ISSUE THREAD

**Issue by wiseodd** [aleximmer/Laplace#196]
Esp.:

1. Format using `isort --profile black .`
2. Format using `ruff format`
3. Lint using `ruff check .`

**Comment by runame** [comment]
Since we added `isort` to the ruff configs, it should be sufficient to run `ruff check --fix .` and `ruff format .`.

**Comment by runame** [comment]
Just added a makefile that bundles the two ruff commands into one (`make ruff`) in #197.

**Comment by wiseodd** [comment]
That's true! Note to self: for `conform.nvim` this translates to:

```diff
formatters_by_ft = {
  python = { 
-    'isort',
+    'ruff_fix', 
    'ruff_format' 
  },
}
```
