### ISSUE TITLE
Optimization of prior noise

### ISSUE THREAD

**Issue by cbuelt** [aleximmer/Laplace#222]
**Issue:**
I noticed strange behavior when optimizing the prior precision and observation noise in my own experiments and especially in the [toy regression example](https://github.com/aleximmer/Laplace/blob/main/examples/regression_example.md). I copied and executed the exact code:
```python 
n_epochs = 1000
torch.manual_seed(711)

# create toy regression data
X_train, y_train, train_loader, X_test = get_sinusoid_example(sigma_noise=0.3)


# construct single layer neural network
def get_model():
    torch.manual_seed(711)
    return torch.nn.Sequential(
        torch.nn.Linear(1, 50), torch.nn.Tanh(), torch.nn.Linear(50, 1)
    )
model = get_model()

# train MAP
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
for i in range(n_epochs):
    for X, y in train_loader:
        optimizer.zero_grad()
        loss = criterion(model(X), y)
        loss.backward()
        optimizer.step()

la = Laplace(model, "regression", subset_of_weights="all", hessian_structure="full")
la.fit(train_loader)
log_prior, log_sigma = (
    torch.ones(1, requires_grad=True),
    torch.ones(1, requires_grad=True),
)
hyper_optimizer = torch.optim.Adam([log_prior, log_sigma], lr=1e-1)
marglik_list = []
for i in range(n_epochs):
    hyper_optimizer.zero_grad()
    neg_marglik = -la.log_marginal_likelihood(log_prior.exp(), log_sigma.exp())
    neg_marglik.backward()
    hyper_optimizer.step()
    marglik_list.append(neg_marglik.item())
marglik_list = np.array(marglik_list)

print(
    f"sigma={la.sigma_noise.item():.2f}",
    f"prior precision={la.prior_precision.item():.2f}",
)

x = X_test.flatten().cpu().numpy()
f_mu, f_var = la(X_test)

f_mu = f_mu.squeeze().detach().cpu().numpy()
f_sigma = f_var.squeeze().detach().sqrt().cpu().numpy()
pred_std = np.sqrt(f_sigma**2 + la.sigma_noise.item() ** 2)

plot_regression(
    X_train, y_train, x, f_mu, pred_std, file_name="regression_example", plot=False
)
```
While the plot is the same as in the example, the optimized values are: (Precision=0.0, Sigma=24240.55). Furthermore, I tracked the negative log likelihood and noticed that it is actually increasing/being maximized instead of being minimized.
![neg_likelihood](https://github.com/user-attachments/assets/bb23aa11-7f08-422a-98e8-ed135dd47ece)

Do I miss something or is there an issue with the optimization procedure, resulting in unreasonable high values for the prior noise, which is also present in the example? You can also see in the [plot](https://aleximmer.github.io/Laplace/#bayesian-predictive) that the predictive noise is much higher than the observation noise. Do you have an idea for why that may be and how to fix it as to tune the prior noise correctly?

**Comment by wiseodd** [comment]
After the recent `asdl` update, the installation from `main` is indeed failing. For now, please install it via

```
pip install git+https://github.com/aleximmer/laplace@update-deps
```

If you want to play around with the source code:

```
git clone git@github.com:aleximmer/Laplace.git
cd Laplace
git checkout update-deps
```

**Comment by cbuelt** [comment]
Thanks a lot, this has indeed fixed my problems.
