### ISSUE TITLE
:heavy_minus_sign: Is `torchaudio` really needed?

### ISSUE THREAD

**Issue by o-laurent** [aleximmer/Laplace#251]
Hello, 

Thanks for your work.

I've seen that `torchaudio` is defined as a dependency in your `pyproject.toml`. Furthermore, its version is explicitly enforced, which is a huge constraint for any library that would use `laplace-torch` as a dependency.

Since GitHub tells me that it's unused throughout the repository, is `torchaudio` really needed?

Best,

Olivier Laurent

**Comment by wiseodd** [comment]
Hi, `torchaudio` shouldn't be needed. Would you like to open a pull request and make sure that all tests pass without `torchaudio`?

**Comment by o-laurent** [comment]
> Hi, `torchaudio` shouldn't be needed. Would you like to open a pull request and make sure that all tests pass without `torchaudio`? 

Yes, I can definitely do this tomorrow! Thank you so much!

**Comment by wiseodd** [comment]
Closed via #255 

Thanks so much for your contribution, @o-laurent!
