### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by izzatum** [AlexImmer/Laplace#33]
Hi! Thank you for developing this module! I experienced an error when trying the Laplace module on Google colab. It says " cannot import name 'Laplace' from 'laplace' (/usr/local/lib/python3.7/dist-packages/laplace/__init__.py)". Kindly seek your assistance in this issue. Thank you!

**Comment by AlexImmer** [comment]
Hi! Thanks for letting us know about this problem. How did you install the package in google colab? I briefly tried with the following command in the first cell which ran fine:
```
!pip install laplace@git+https://github.com/AlexImmer/Laplace.git
```
And after that `from laplace import Laplace` worked for me.

**Comment by izzatum** [comment]
Hi! Great thanks for the solution! It works for me as well. 

Previously, I used `!pip install laplace` without the git.

Thanks!
