### ISSUE TITLE
How do you avoid negative determinant of hessian?

### ISSUE THREAD

**Issue by moskomule** [AlexImmer/Laplace#37]
Hi, I have a question about how do you avoid negative determinants of Hessian for logdetermiant.

Hessian matrices are not always positive semi-definite, so generally, they have both positive and negative eigenvalues. In other words, determinants can sometimes be negative, i.e., logdet of Hessians cannot be obtained. As long as I ran some simple experiments with your code, I didn't encounter such an issue, but I'd like to know how do you avoid this problem.

Thank you!

**Comment by runame** [comment]
Hi, thanks a lot for reaching out! 

We only implement two approximations to the Hessian, i.e. the generalized Gauss Newton (GGN) matrix (which is equivalent to the Fisher information matrix for the implemented likelihoods) and the empirical Fisher (EF). Both, the GGN and the EF are guaranteed to be positive semi-definite.  If you are not familiar with these approximations, please see section 2.1 in our [paper](https://arxiv.org/pdf/2106.14806.pdf) for a brief introduction to them and further references.

You can choose which approximation you want to use by specifying the [`backend`](https://aleximmer.github.io/Laplace/#laplace.BaseLaplace) keyword of the `Laplace` function. Currently, we offer implementations with [BackPack](https://github.com/f-dangel/backpack/) and [ASDL](https://github.com/kazukiosawa/asdfghjkl); you can take a look at the code of the available backends [here](https://github.com/AlexImmer/Laplace/tree/main/laplace/curvature).

Let me know if you have any other questions.

**Comment by moskomule** [comment]
Hi, thanks for the prompt reply. I didn't notice that the positive semi-definiteness was thanks to the approximations. That's very helpful information because I'm not so familiar with these Hessian approximations.
Thank you again.

**Comment by runame** [comment]
Great, glad I could help. I will close this issue now. Feel free to open a new one if more questions arise.
