### ISSUE TITLE
Allow fitting Laplace repeatedly

### ISSUE THREAD

**Issue by AlexImmer** [AlexImmer/Laplace#40]
There is no reason to prefent the `.fit()` method to be called repeatedly, for example after changing hyperparameters or on a different data set. Currently, this raises a `ValueError` [here](https://github.com/AlexImmer/Laplace/blob/b21d415df47e1b4049533e77d78945c391bd6859/laplace/baselaplace.py#L115). Maybe raise a warning instead of simply reset the state to enable safe iterative fits.

**Comment by runame** [comment]
Fixed by #62.
