### ISSUE TITLE
How to compute and store the Hessian for last layer LA offline and use it for future predictions

### ISSUE THREAD

**Issue by roysubhankar** [AlexImmer/Laplace#42]
Hello,

Thanks for the amazing library.

I want to first fit the Last Layer Laplace with the training data and then would like to store the essentials (e.g. the Hessian and the mu) and then later use the _glm_predictive_distribution() function with another OOD dataset in a separate python file, without having access to the training data. Could you please me to understand if this decoupling would be possible with the current code? If possible, can you please point me to the metric/variables which I would need to store?

**Comment by panos108** [comment]
I had the same issue. It seems that the dill solved thanks!

**Comment by runame** [comment]
Perfect, thanks for letting me know!
