### ISSUE TITLE
Integration of `asdfghjkl-0.1`

### ISSUE THREAD

**Issue by aleximmer** [aleximmer/Laplace#44]
Current version can be found [here](https://github.com/kazukiosawa/asdfghjkl/tree/0.1). For example, Kazuki Osawa mentioned that the `data_average` parameter now defaults to `True` but we require `False` for a proper Hessian approximation.

**Comment by AlexImmer** [comment]
Kazuki postponed the release of the next version of his library to end of January/beginning of February. This issue is therefore removed from NeurIPS pre-release.

**Comment by wiseodd** [comment]
This is part of #144. The `mc-subset2` of that PR was a branch of `integrate-asdl-latest`. Once it's merged, this should be closed.
