### ISSUE TITLE
Add methods to save and load Laplace instances

### ISSUE THREAD

**Issue by runame** [aleximmer/Laplace#45]
Users might want to avoid computing the Hessian approximation every time they run their code or reuse the same Laplace approximation in different files (e.g. #42). The best interface would probably be `.save(filepath)` and `.load(filepath)` methods.

**Comment by wiseodd** [comment]
@runame @aleximmer do you have a sketch already on how to accomplish this? I'm willing to work on this. 

It will be very useful for LLMs etc since their forward passes are already quite expensive => fitting Laplace each time running a script is really tiring...

**Comment by runame** [comment]
Addressed by #148.
