### ISSUE TITLE
KMP_DUPLICATE_LIB

### ISSUE THREAD

**Issue by caxelrud** [AlexImmer/Laplace#56]
Hi,
To make it work, I had to add the following:
```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

```
Check the following link:
[error 15 initializing-libiomp5md-dll](https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial)

**Comment by AlexImmer** [comment]
Hi. Can you explain what error message you got and the environment you used (OS, python version, conda?)? Any details would be helpful to reproduce this and eventually fix it.

**Comment by caxelrud** [comment]
Environment is:
OS: Windows 10
Python: 3.8.12
Conda: 4.10.3
torch: 1.8.1
numpy: 1.21.2
