### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by caxelrud** [AlexImmer/Laplace#57]
Hi,
Are you going to add more examples here?
I will try myself same ones (originally tested with [BNN](https://github.com/JavierAntoran/Bayesian-Neural-Networks), Pymc3/BNN or Julia/Turing/BNN)  : 
- Toy (Javier Antoran Cabiscol)
- Yacht (UCI)
- Housing (UCI)
- Half Moons (sklearn)
- Toy (Turing)

**Comment by AlexImmer** [comment]
Yes, we will also add more examples. Happy to receive contributions on more examples. Ideally, individual examples should be submitted as individual PRs.
