### ISSUE TITLE
Progress bar for Laplace fitting

### ISSUE THREAD

**Issue by edaxberger** [AlexImmer/Laplace#67]
It would be nice to (have the option to) print a progress bar when fitting the Hessian (e.g. via `tqdm`).
For small problems this doesn't matter as it's instant anyways, but for larger problems one can wait a considerable time for the fitting and doesn't really know how long it'll take.

**Comment by AlexImmer** [comment]
I think you could achieve this with 
```python
train_loader_tqdm = tqdm(train_loader)
setattr(train_loader_tqdm, 'dataset', train_loader.dataset) 
lap.fit(train_loader_tqdm)
```
The `setattr` line is weird but this is due to us requiring the dataset attribute to get the number of samples `N` which is also a discussed requirement #83.

**Comment by edaxberger** [comment]
Yes you're right, this is quite easy to achieve externally, so there's no need to provide this option internally at this point.
