### ISSUE TITLE
AsdlHessian data and model on separate devices

### ISSUE THREAD

**Issue by UppalAnshuk** [AlexImmer/Laplace#73]
Hi guys,
I have been playing around with this library(it's really good!).
This is just a small thing but when losses are calculated in the [eig_lowrank](https://github.com/AlexImmer/Laplace/blob/7e42de812032cbf5d1214b89fe9cbd181c461942/laplace/curvature/asdl.py#L158)
in asdl.py I think the data and the model are not on the same device because a train_loader is passed to the eig_lowrank function. A simple change - .to(device) would make it work. 

Keep up the good work! :)

**Comment by runame** [comment]
Hi Anshuk, glad you like the library. Nice catch, I just fixed it in the linked PR.

Thanks a lot!
