### ISSUE TITLE
Is there a significant improvement when testing on ImageNet?

### ISSUE THREAD

**Issue by chuong98** [AlexImmer/Laplace#84]
Hi, thanks for releasing the lib.
It will be great if you can demonstrate the superior of LA on large scale dataset, such as ImageNet or VisualGenome?
Thank you.

**Comment by runame** [comment]
Hi, you can find results for one particular flavor of LA (last-layer + K-FAC GGN + multi-class probit approximation) on (corrupted) ImageNet in [Mixtures of Laplace Approximations for Improved Post-Hoc Uncertainty in Deep Learning](https://arxiv.org/abs/2111.03577), see Appendix D.2 and Figure 9. It is only compared against MAP, deep ensemble, and MoLA (ensemble of LAs), but maybe it is still interesting to you.
