### ISSUE TITLE
Using Laplace in knowledge graph embedding models

### ISSUE THREAD

**Issue by Demirrr** [AlexImmer/Laplace#90]
Dear all,

Thank you for this open-source project. I did enjoy your paper and [presentation](https://www.youtube.com/watch?v=nMONiYLWWOU). I wanted to use laplace API to calibrate knowledge graph embedding (KGE) models in the link prediction task. Yet, I could not do it yet. In below, I aimed to briefly described the situation

```python
class DistMult(BaseKGE):
    def __init__(self, args):
        super().__init__(args.learning_rate)
        self.name = 'DistMult'
        self.loss = torch.nn.BCEWithLogitsLoss()
        self.embedding_dim = args.embedding_dim
        self.emb_ent_real = nn.Embedding(args.num_entities, args.embedding_dim)
        self.emb_rel_real = nn.Embedding(args.num_relations, args.embedding_dim) 
        ...
    def forward_k_vs_all(self, x):
        e1_idx, rel_idx = x[:, 0], x[:, 1]
        # (1)
        # (1.1) Real embeddings of head entities
        emb_head_real = self.input_dp_ent_real(self.bn_ent_real(self.emb_ent_real(e1_idx)))
        # (1.2) Real embeddings of relations
        emb_rel_real = self.input_dp_rel_real(self.bn_rel_real(self.emb_rel_real(rel_idx)))
        # (2) Compute logits
        return torch.mm(self.hidden_dropout(self.bn_hidden_real(emb_head_real * emb_rel_real)),
                        self.emb_ent_real.weight.transpose(1, 0))
```
where 
```python
class BaseKGE(pl.LightningModule): ...
```
`forward_k_vs_all(self, x)` returns a 2D torch.tensor. After the model is trained , the below part is executed 
```python
from laplace import Laplace
  la = Laplace(model, 'classification',
               subset_of_weights='all',
               hessian_structure='diag')
  la.fit(dataset.train_dataloader())
```
and  **NotImplementedError(NotImplementedError: Extension saving to diag_ggn_exact does not have an extension for Module <class 'core.models.real.DistMult'>** is raised.

Similarly, using   
```python
la = Laplace(model, 'classification',subset_of_weights='subnetwork',hessian_structure='full')
``` 
raises **TypeError: __init__() missing 1 required positional argument: 'subnetwork_indices'**

I was wondering whether you have any suggestion pertaining the above descired problem.

Cheers!

**Comment by georgezefko** [comment]
For your question regarding the subnetwork you are missing an argument "subnetwork_indices". Before Laplace you need to apply the following steps first
subnetwork_mask = ModuleNameSubnetMask(model, module_names=module_name (eg. 'fc1')
subnetwork_mask.select()
subnetwork_indices = subnetwork_mask.indices

**Comment by Demirrr** [comment]
@georgezefko Very appreciated. Problem is solved!
