### ISSUE TITLE
Support ASDL for regression

### ISSUE THREAD

**Issue by hnisonoff** [aleximmer/Laplace#97]
Is it possible to add support for ASDL for regression? I have a model that I cannot put into Sequential due to the need to transpose some dimensions at an intermediate layer (which I think cannot be done in Sequential).

**Comment by AlexImmer** [comment]
Hi Hunter. It will be possible hopefully soon once the latest features are merged into the `asdfghjkl` backend. We already have a preliminary integration of the latest version on this branch https://github.com/AlexImmer/Laplace/tree/integrate-latest-asdl. It worked with the current `0.1` branch on `asdfghjkl`: https://github.com/kazukiosawa/asdfghjkl/tree/0.1. But note that this is still in development/integration phase and I cannot guarantee it currently works.

**Comment by AlexImmer** [comment]
Also, see the limitations at the time of the last integration: https://github.com/AlexImmer/Laplace/pull/47

**Comment by runame** [comment]
Included in #44.
