### ISSUE TITLE
Paper Equation 7 Typo

### ISSUE THREAD

**Issue by HanGuo97** [AlexImmer/Laplace#98]
Hi, thanks for the awesome library and writeup!

I noticed that in Equation 7, there is a minus sign before `gamma^{-2}`. Is this a typo -- I would assume it should be the following one (with the leading negative sign removed)?

![image](https://user-images.githubusercontent.com/18187806/167276223-a91b8f6d-1d73-4ccb-bf3a-abb73271499e.png)

**Comment by wiseodd** [comment]
Hi, thanks for noticing that. You're right, the negative signs from inside the exponent in the prior and from the fact that `L` is the negative log-posterior, cancel.

**Comment by HanGuo97** [comment]
Got it -- thanks for the confirmation!
